name: spid_cie_oidc

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, closed ]
  push:
    paths-ignore:
      - README.md
      - CHANGELOG.md  # Should never be edited anyway
      - .gitignore
      - .github/**
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        dotnet-version:
          - '3.1.x'
          - '5.0.x'
          - '6.0.x'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET ${{ matrix.python-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --no-restore
      working-directory: src
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src
