name: spid_cie_oidc

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        dotnet-version:
          - '3.1.x'
          - '5.0.x'
          - '6.0.x'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET ${{ matrix.python-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
