name: spid_cie_oidc

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, closed ]
  push:
    paths-ignore:
      - README.md
      - CHANGELOG.md  # Should never be edited anyway
      - .gitignore
      - .github/**
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --no-restore
      working-directory: src
    - name: Test
      run: dotnet test --no-build --verbosity normal -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover
      working-directory: src
    - name: Copy the opencover.xml file
      run: |
        find ./ -type f -name "coverage.opencover.xml" | while read fname; do
          dirname=`dirname "$fname"`
          cp "${dirname}/coverage.opencover.xml" "./coverage.opencover.xml"
        done
    - name: Create Test Coverage Badge
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: create_coverage_badge
      with:
        label: Unit Test Coverage
        color: brightgreen
        path: ./coverage.opencover.xml      
    - name: Print code coverage
      run: echo "Code coverage percentage ${{steps.create_coverage_badge.outputs.percentage}}%"
    - name: Print code coverage data
      run: echo "Code coverage percentage ${{steps.create_coverage_badge.outputs.badge}}%"
    - name: Create A File
      uses: 1arp/create-a-file-action@0.2
      with:
        path: ./.github
        file: coverage_badge
        content: ${{steps.create_coverage_badge.outputs.badge}}%
    - name: Commit coverage_badge
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'githubaction@users.noreply.github.com'
        git add ./.github/coverage_badge
        git commit -am "Automated Code Coverage badge data push"
        git push
